export const COUNTRIES = [
  { name: 'Pakistan', code: 'pk', emoji: '🇵🇰' },
  { name: 'India', code: 'in', emoji: '🇮🇳' },
  { name: 'United States', code: 'us', emoji: '🇺🇸' },
  { name: 'United Kingdom', code: 'gb', emoji: '🇬🇧' },
  { name: 'Canada', code: 'ca', emoji: '🇨🇦' },
  { name: 'Australia', code: 'au', emoji: '🇦🇺' },
  { name: 'Saudi Arabia', code: 'sa', emoji: '🇸🇦' },
  { name: 'United Arab Emirates', code: 'ae', emoji: '🇦🇪' },
  { name: 'Bangladesh', code: 'bd', emoji: '🇧🇩' },
  { name: 'Turkey', code: 'tr', emoji: '🇹🇷' },
  { name: 'Germany', code: 'de', emoji: '🇩🇪' },
  { name: 'France', code: 'fr', emoji: '🇫🇷' },
  { name: 'China', code: 'cn', emoji: '🇨🇳' },
  { name: 'Indonesia', code: 'id', emoji: '🇮🇩' },
  { name: 'Malaysia', code: 'my', emoji: '🇲🇾' },
  { name: 'Nigeria', code: 'ng', emoji: '🇳🇬' },
  { name: 'Egypt', code: 'eg', emoji: '🇪🇬' },
  { name: 'Iran', code: 'ir', emoji: '🇮🇷' },
  { name: 'Afghanistan', code: 'af', emoji: '🇦🇫' },
  { name: 'Netherlands', code: 'nl', emoji: '🇳🇱' },
  { name: 'Spain', code: 'es', emoji: '🇪🇸' },
  { name: 'Italy', code: 'it', emoji: '🇮🇹' },
  { name: 'Brazil', code: 'br', emoji: '🇧🇷' },
  { name: 'South Africa', code: 'za', emoji: '🇿🇦' },
  { name: 'Kenya', code: 'ke', emoji: '🇰🇪' },
  { name: 'Ghana', code: 'gh', emoji: '🇬🇭' },
  { name: 'Qatar', code: 'qa', emoji: '🇶🇦' },
  { name: 'Kuwait', code: 'kw', emoji: '🇰🇼' },
  { name: 'Bahrain', code: 'bh', emoji: '🇧🇭' },
  { name: 'Oman', code: 'om', emoji: '🇴🇲' },
  { name: 'Jordan', code: 'jo', emoji: '🇯🇴' },
  { name: 'Iraq', code: 'iq', emoji: '🇮🇶' },
  { name: 'Syria', code: 'sy', emoji: '🇸🇾' },
  { name: 'Sri Lanka', code: 'lk', emoji: '🇱🇰' },
  { name: 'Nepal', code: 'np', emoji: '🇳🇵' },
  { name: 'Philippines', code: 'ph', emoji: '🇵🇭' },
  { name: 'Singapore', code: 'sg', emoji: '🇸🇬' },
  { name: 'Japan', code: 'jp', emoji: '🇯🇵' },
  { name: 'South Korea', code: 'kr', emoji: '🇰🇷' },
  { name: 'Russia', code: 'ru', emoji: '🇷🇺' },
];
